    name: Docker Hub Image Build
    on:
      push:
        branches:
          - main
     
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          - run: docker build -t fujayelk/client-test -f Dockerfile.dev ./client
          - run: docker run -e CI=true fujayelk/client-test npm test

          - name: Build production docker images
            run: docker build -t fujayelk/multi-client -f Dockerfile.dev ./client
            run: docker build -t fujayelk/multi-nginx -f Dockerfile.dev ./nginx
            run: docker build -t fujayelk/multi-server -f Dockerfile.dev ./server
            run: docker build -t fujayelk/multi-worker -f Dockerfile.dev ./worker

          - name: Push images to docker hub
            run: docker push fujayelk/multi-client
            run: docker push fujayelk/multi-nginx
            run: docker push fujayelk/multi-server
            run: docker push fujayelk/multi-worker
     
#          - name: Generate deployment package
#            run: zip -r deploy.zip . -x '*.git*'
#     
#          - name: Deploy to EB
#            uses: einaregilsson/beanstalk-deploy@v18
#            with:
#              aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#              aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
#              application_name: docker-react
#              environment_name: docker-react-env
#              existing_bucket_name: elasticbeanstalk-eu-north-1-699083849445
#              region: eu-north-1
#              version_label: ${{ github.sha }}
#              deployment_package: deploy.zip